better handle stop and shutdown

diff --git a/etc/mhvtl.in b/etc/mhvtl.in
--- a/etc/mhvtl.in
+++ b/etc/mhvtl.in
@@ -330,6 +330,53 @@ CONF_SAMPLE
 	fi
 done
 
+proc_wait_stop() {
+	local PID=$1
+	[ -z "$PID" ] && return 1
+	local i=0
+	local MAX=$2
+	[ -z "$MAX" ] && MAX=90
+	while kill -0 "$PID" 2>/dev/null; do
+		[ $i = "$MAX" ] && return 2
+		sleep 1
+		i=$((i+1))
+	done
+	return 0
+}
+
+stop() {
+	local a
+	local r=0
+	local output=`ps -o pid,cmd -C vtltape --no-headers | awk '/vtltape -q/ {print $1"_"$4}'`
+	local s=`ps -o pid,cmd -C vtllibrary --no-headers | awk '/vtllibrary -q/ {print $1"_"$4}'`
+	output="$output $s"
+
+	for s in $output
+	do
+		a=(${s//_/ })
+		echo "   Sending exit to ${a[1]}"
+		vtlcmd ${a[1]} exit
+		usleep 100
+		h=1
+	done
+
+	[ -n "$a" ] && sleep 1
+
+	for s in $output
+	do
+		a=(${s//_/ })
+		if ! proc_wait_stop "${a[0]}"; then
+			kill "${a[0]}" >/dev/null 2>&1
+			echo "   WARNING: can't stop pid ${a[0]}"
+			r=1
+		fi
+	done
+
+	return $r
+}
+
+RET=0
+
 case "$1" in
     start)
 	if [ ! -e /sys/module/mhvtl  ]; then
@@ -373,10 +420,9 @@ case "$1" in
 	fi
 
 	# Should be proof against 'vi vtltape' match
-	if [ ! -z "`ps -eo cmd|awk '/vtllibrary|vtltape/ {print $1}'|egrep 'vtltape|vtllibrary'`" ];
-	then
+	if ps -o pid -C vtllibrary --no-headers >/dev/null 2>&1; then
 		echo "mhvtl already running..."
-		exit 1
+		exit 0
 	fi
 
 	chown -R $USER:$USER $MHVTL_CONFIG_PATH
@@ -396,78 +442,43 @@ case "$1" in
 		exit 1
 	fi
 
-	if [ -f /etc/rc.status ]; then
-		rc_status -v
-	fi
+	[ -f /etc/rc.status ] && rc_status -v
 	;;
 
     reload)
-	for a in `ps -o pid -C vtllibrary --no-headers`
-	do
-		echo "   Sending reload to $a"
-		kill -SIGHUP $a
-	done
+		for a in `ps -o pid -C vtllibrary --no-headers`
+		do
+			echo "   Sending reload to $a"
+			kill -SIGHUP $a
+		done
 	;;
 
     stop)
-        echo "shutdown of mhvtl"
+		echo "shutdown of mhvtl"
+		stop
+		RET=$?
 
-	if [ -z "`ps --user $USER|grep -v TIME`" ]; then
-		echo "mhvtl not running..."
-		exit 0
-	fi
-
-	for a in `ps -eo cmd |awk '/^vtltape -q/ {print $3}'`
-	do
-		echo "   Sending exit to $a"
-		vtlcmd $a exit
-		usleep 100 > /dev/null 2>&1 /dev/null
-	done
-
-	for a in `ps -eo cmd |awk '/^vtllibrary -q/ {print $3}'`
-	do
-		echo "   Sending exit to $a"
-		vtlcmd $a exit
-		usleep 100 > /dev/null 2>&1 /dev/null
-	done
-
-	if [ -f /etc/rc.status ]; then
-		rc_status -v
-	fi
+		[ -f /etc/rc.status ] && rc_status -v
 	;;
     shutdown)
-	# Remove kernel module (mhvtl) along with messageQ key.
-        echo "Removing mhvtl kernel module"
-	for a in `ps -eo cmd |awk '/^vtltape -q/ {print $3}'`
-	do
-		echo "   Sending exit to $a"
-		vtlcmd $a exit
-		usleep 100 > /dev/null 2>&1 /dev/null
-	done
+		# Remove kernel module (mhvtl) along with messageQ key.
+		echo "Removing mhvtl kernel module"
+		stop
+		RET=$?
 
-	for a in `ps -eo cmd |awk '/^vtllibrary -q/ {print $3}'`
-	do
-		echo "   Sending exit to $a"
-		vtlcmd $a exit
-		usleep 100 > /dev/null 2>&1 /dev/null
-	done
+		# Sleep long enough for the daemons to see the exit commands.
+		sleep 1
 
-	# Sleep long enough for the daemons to see the exit commands.
-	sleep 1
+		rmmod mhvtl
+		Q_EXISTS=`ipcs -q | awk '/4d61726b/ {print $2}'`
+		[ -n "$Q_EXISTS" ] && ipcrm -q $Q_EXISTS
 
-	rmmod mhvtl
-	Q_EXISTS=`ipcs -q | awk '/4d61726b/ {print $2}'`
-	if [ "X$Q_EXISTS" != "X" ]; then
-		ipcrm -q $Q_EXISTS
-	fi
-	if [ -f /etc/rc.status ]; then
-		rc_status -v
-	fi
+		[ -f /etc/rc.status ] && rc_status -v
 	;;
     *)
-	echo "Usage: $0 {start|reload|stop|shutdown}"
-	exit 1
+		echo "Usage: $0 {start|reload|stop|shutdown}"
+		exit 1
 esac
-if [ -f /etc/rc.status ]; then
-	rc_exit
-fi
+
+[ -f /etc/rc.status ] && rc_exit
+exit $RET
